import { Asset } from 'expo-asset';
import * as FileSystem from 'expo-file-system/legacy';
import {
  formatTrackdayPrepSummary,
  type TrackdayPrepDraft,
} from '../storage/trackdayPrep';

let cachedLogoDataUri: string | null = null;

async function getRrLogoDataUri(): Promise<string> {
  if (cachedLogoDataUri) return cachedLogoDataUri;
  const asset = Asset.fromModule(require('../assets/RR.png'));
  await asset.downloadAsync();
  const uri = asset.localUri ?? asset.uri;
  if (!uri) throw new Error('Could not load RoadRacer logo.');
  const b64 = await FileSystem.readAsStringAsync(uri, {
    encoding: FileSystem.EncodingType.Base64,
  });
  cachedLogoDataUri = `data:image/png;base64,${b64}`;
  return cachedLogoDataUri;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function formatReportBodyHtml(reportText: string): string {
  const escaped = escapeHtml(reportText.trim());
  return escaped
    .split(/\n{2,}/)
    .map((block) => {
      const withBreaks = block.replace(/\n/g, '<br/>');
      if (/^#{1,3}\s/.test(block) || /^How to get the best/i.test(block.trim())) {
        return `<h2>${withBreaks.replace(/^#+\s*/, '')}</h2>`;
      }
      return `<p>${withBreaks}</p>`;
    })
    .join('\n');
}

export async function buildTrackdayPrepReportHtml(
  draft: TrackdayPrepDraft,
  reportText: string
): Promise<string> {
  const logo = await getRrLogoDataUri();
  const summary = escapeHtml(formatTrackdayPrepSummary(draft)).replace(/\n/g, '<br/>');
  const body = formatReportBodyHtml(reportText);

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>RoadRacer Trackday Prep — ${escapeHtml(draft.trackName)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #0f172a; margin: 32px; line-height: 1.45; }
    .logo { width: 72px; height: 72px; display: block; margin: 0 auto 12px; }
    h1 { text-align: center; font-size: 22px; margin: 0 0 4px; }
    .sub { text-align: center; color: #475569; margin-bottom: 24px; font-size: 14px; }
    .card { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 14px 16px; margin-bottom: 20px; font-size: 13px; }
    h2 { font-size: 16px; margin: 18px 0 8px; color: #1e293b; }
    p { margin: 0 0 12px; font-size: 14px; }
    .footer { margin-top: 28px; font-size: 11px; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 12px; }
  </style>
</head>
<body>
  <img class="logo" src="${logo}" alt="RoadRacer" />
  <h1>RoadRacer Trackday Prep</h1>
  <div class="sub">${escapeHtml(draft.trackName)} · ${escapeHtml(draft.dateIso)}</div>
  <div class="card">${summary}</div>
  ${body}
  <div class="footer">Generated by RoadRacer · Private until you share</div>
</body>
</html>`;
}
