/**
 * Seed Q&A for trivia bank: easy and hard. Used by buildTriviaBank.js to build 500 easy + 500 hard.
 * Format: [ { q, a }, ... ]
 */

export const FUNNY_ANSWERS = [
  'A unicycle with a jet engine.',
  'Whatever the manual says.',
  'Ducati\'s marketing department.',
  'Your mum on a scooter.',
  'The opposite of slow.',
  'Something you tell your insurance company.',
  'Where the chicken crossed the road.',
  'A really fast mobility scooter.',
  'The thing you blame when you lowside.',
  'What the marshals wave when they\'re bored.',
  'A place where knee sliders go to die.',
  'The same as walking, but louder.',
  'Something you can\'t afford after the crash.',
  'The best excuse for leather pants.',
  'How you get to the apex of the couch.',
  'What happens when you forget to close the pit lane.',
  'A slipstream to the pub.',
  'The warm-up lap for your nap.',
  'Body position: still in bed.',
  'Trail braking into the driveway.',
  'A chicane in the cereal aisle.',
  'The green flag at the traffic lights.',
  'Whatever Rossi says it is.',
  'The sound of your bank account emptying.',
  'A track day for hedgehogs.',
  'Red flag: pizza arrived.',
  'Hot pit: petrol station past midnight.',
  'Pick up the bike? I dropped the remote.',
  'A track day org? The local bingo hall.',
  'Knee slider: for opening beer bottles.',
  'Something you Google after the briefing.',
  'The thing that was definitely the tyre\'s fault.',
  'Where you store your ego.',
  'A very expensive way to get a tan.',
  'The opposite of a sensible life choice.',
];

export const EASY_QA = [
  { q: 'What does BP mean in motorcycle riding?', a: 'Body position. Leaning off the bike into the corner to help turn and keep the bike more upright.' },
  { q: 'What is trail braking?', a: 'Carrying a small amount of front brake into the turn after turn-in, then releasing gradually.' },
  { q: 'What is the apex of a corner?', a: 'The point where the bike is closest to the inside of the corner.' },
  { q: 'What does hot pit mean?', a: 'A quick stop in the pit lane without going to the garage.' },
  { q: 'What is a knee slider for?', a: 'Protection and a reference for lean angle.' },
  { q: 'What does green flag mean?', a: 'Track is live; racing or session is on.' },
  { q: 'What is a chicane?', a: 'A tight S-shaped section of track used to slow bikes.' },
  { q: 'What does red flag mean?', a: 'Session stopped. Slow down, no passing, return to pit.' },
  { q: 'What is a slipstream?', a: 'Riding in the air pocket behind another bike to reduce drag.' },
  { q: 'What is a warm-up lap?', a: 'A lap before the race or session to warm tires.' },
  { q: 'What does pick up the bike mean?', a: 'Stand the bike up to finish the corner and get on the gas.' },
  { q: 'What is a track day org?', a: 'Organization that rents the circuit and runs the day.' },
  { q: 'What is a track day?', a: 'A supervised session on a closed circuit, usually with groups by pace.' },
  { q: 'What is the racing line?', a: 'The fastest path through a corner: outside to inside (apex) to outside.' },
  { q: 'What is MotoGP?', a: 'The premier class of FIM road racing world championship.' },
  { q: 'What is WorldSBK?', a: 'FIM Superbike World Championship.' },
  { q: 'What is the Isle of Man TT?', a: 'A famous time-trial motorcycle race on public roads on the Isle of Man.' },
  { q: 'What is a superbike?', a: 'A large-engine production-based racing motorcycle, typically 1000 cc.' },
  { q: 'What is a sidecar in racing?', a: 'A three-wheeled machine with a passenger sidecar; raced in its own class.' },
  { q: 'What is a pit stop?', a: 'A stop in the pits for fuel, tyres, or repairs during a race or session.' },
  { q: 'What is pole position?', a: 'The first grid position, earned by the fastest qualifier.' },
  { q: 'What is a fastest lap?', a: 'The quickest lap time set during a race or session.' },
  { q: 'What is a grand prix?', a: 'A major race, especially in the world championship calendar.' },
  { q: 'What is a constructor championship?', a: 'A title for the motorcycle manufacturer with the most points.' },
  { q: 'What is a rider championship?', a: 'The title for the rider with the most points in a series.' },
  { q: 'What is a DNF?', a: 'Did not finish.' },
  { q: 'What is a DNS?', a: 'Did not start.' },
  { q: 'What is a black flag?', a: 'A flag requiring a rider to leave the track or report to the pits.' },
  { q: 'What is a yellow flag?', a: 'Caution; no passing, hazard on or near the track.' },
  { q: 'What is a blue flag?', a: 'Faster rider behind; let them pass.' },
  { q: 'What is a white flag?', a: 'Often one lap to go, or slow vehicle on track.' },
  { q: 'What is a chequered flag?', a: 'End of the race or session.' },
  { q: 'What is a lap record?', a: 'The fastest lap time ever set at a circuit in a given class.' },
  { q: 'What is a race lap?', a: 'One complete circuit of the track during a race.' },
  { q: 'What is a qualifying session?', a: 'A timed session used to set the starting grid.' },
  { q: 'What is a practice session?', a: 'A session for riders to learn the track and set up the bike.' },
  { q: 'What is a start line?', a: 'The line from which the race begins.' },
  { q: 'What is a finish line?', a: 'The line where the race ends.' },
  { q: 'What is a grid?', a: 'The ordered starting positions for the race.' },
  { q: 'What is a standing start?', a: 'A start from a standstill with engines running.' },
  { q: 'What is a rolling start?', a: 'A start where riders are already moving behind a safety car or pace vehicle.' },
  { q: 'What is a safety car?', a: 'A car that leads the field at reduced speed during a caution period.' },
  { q: 'What is a marshal?', a: 'A track-side official who waves flags and assists in incidents.' },
  { q: 'What is gravel trap?', a: 'A run-off area filled with gravel to slow bikes that leave the track.' },
  { q: 'What is a run-off area?', a: 'An area beside the track for riders who run wide or crash.' },
  { q: 'What is a tyre wall?', a: 'Barrier of tyres used to absorb impact.' },
  { q: 'What is lean angle?', a: 'The angle at which the bike is tilted from vertical in a corner.' },
  { q: 'What is countersteering?', a: 'Pushing the handlebar to make the bike lean and turn.' },
  { q: 'What is throttle control?', a: 'Smooth use of the throttle to manage power and grip.' },
  { q: 'What is engine braking?', a: 'Slowing by closing the throttle so the engine resists.' },
  { q: 'What is a downshift?', a: 'Changing to a lower gear, usually when slowing.' },
  { q: 'What is a rev limiter?', a: 'A device that limits maximum engine rpm.' },
  { q: 'What is a quick shifter?', a: 'A system that allows upshifts without using the clutch.' },
  { q: 'What is a slipper clutch?', a: 'A clutch that reduces rear-wheel lock on aggressive downshifts.' },
  { q: 'What is traction control?', a: 'Electronic system that limits wheel spin.' },
  { q: 'What is wheelie control?', a: 'Electronic system that limits front wheel lift.' },
  { q: 'What is ABS?', a: 'Anti-lock braking system; prevents wheels locking under braking.' },
  { q: 'What is a fairing?', a: 'The bodywork that wraps around the bike for aerodynamics and protection.' },
  { q: 'What is a windscreen?', a: 'The screen in front of the rider to deflect wind.' },
  { q: 'What is a tank?', a: 'The fuel tank, often straddled by the rider.' },
  { q: 'What is a seat unit?', a: 'The rear part of the bike that includes the seat and tail.' },
  { q: 'What is a swingarm?', a: 'The rear suspension linkage that holds the rear wheel.' },
  { q: 'What is a fork?', a: 'The front suspension that holds the front wheel.' },
  { q: 'What is a chain?', a: 'Drives the rear wheel from the gearbox on many bikes.' },
  { q: 'What is a belt drive?', a: 'A belt used instead of a chain to drive the rear wheel.' },
  { q: 'What is shaft drive?', a: 'A driveshaft instead of chain or belt to drive the rear wheel.' },
  { q: 'What is cc in engines?', a: 'Cubic centimetres; engine displacement volume.' },
  { q: 'What is horsepower?', a: 'A measure of engine power.' },
  { q: 'What is torque?', a: 'A measure of rotational force from the engine.' },
  { q: 'What is rpm?', a: 'Revolutions per minute; engine speed.' },
  { q: 'What is a four-stroke engine?', a: 'An engine with intake, compression, power, and exhaust strokes.' },
  { q: 'What is a two-stroke engine?', a: 'An engine that completes a cycle in two strokes.' },
  { q: 'What is an inline-four?', a: 'Four cylinders in a line.' },
  { q: 'What is a V-twin?', a: 'Two cylinders in a V configuration.' },
  { q: 'What is a boxer engine?', a: 'Engine with cylinders opposed horizontally (e.g. BMW).' },
  { q: 'What is a single?', a: 'A single-cylinder engine.' },
  { q: 'What is a parallel twin?', a: 'Two cylinders side by side.' },
  { q: 'What is a triple?', a: 'Three cylinders, often in a line.' },
  { q: 'What is a V4?', a: 'Four cylinders in a V configuration.' },
  { q: 'What is homologation?', a: 'Making a bike legal for a racing class by building a minimum number for the road.' },
  { q: 'What is a production bike?', a: 'A bike built for the public, not a one-off racer.' },
  { q: 'What is a works team?', a: 'A factory-backed team with official manufacturer support.' },
  { q: 'What is a privateer?', a: 'A rider or team without full factory backing.' },
  { q: 'What is a wildcard entry?', a: 'A one-off or extra entry not in the full championship.' },
  { q: 'What is a test rider?', a: 'A rider who develops the bike and tests new parts.' },
  { q: 'What is a team order?', a: 'An instruction from the team to riders (e.g. to swap positions).' },
  { q: 'What is a podium?', a: 'The top three finishing positions (1st, 2nd, 3rd).' },
  { q: 'What is a rostrum?', a: 'The physical stage where the top three stand after the race.' },
  { q: 'What is champagne spray?', a: 'Tradition of spraying champagne on the podium.' },
  { q: 'What is a photo finish?', a: 'When the finish is so close it is decided by a photo.' },
  { q: 'What is a dead heat?', a: 'When two riders finish in exactly the same position/time.' },
  { q: 'What is a penalty?', a: 'A punishment (e.g. time or position) for a rule infringement.' },
  { q: 'What is a ride-through penalty?', a: 'Rider must enter the pits and ride through without stopping.' },
  { q: 'What is a time penalty?', a: 'Time added to the rider\'s race time.' },
  { q: 'What is a grid penalty?', a: 'Rider must start from further back on the grid.' },
  { q: 'What is a black flag with orange disc?', a: 'Mechanical problem; rider must return to pits.' },
  { q: 'What is a lowside?', a: 'A crash where the bike slides out from under the rider (usually rear).' },
  { q: 'What is a highside?', a: 'A crash where the rider is thrown over the bike (often after grip returns).' },
  { q: 'What is a tank slapper?', a: 'Violent oscillation of the handlebars.' },
  { q: 'What is a stoppie?', a: 'Stopping so hard the rear wheel lifts.' },
  { q: 'What is a wheelie?', a: 'Lifting the front wheel off the ground under acceleration.' },
  { q: 'What is an endo?', a: 'Short for end-over-end; often used for a stoppie.' },
  { q: 'What is a burnout?', a: 'Spinning the rear wheel while stationary or moving slowly.' },
  { q: 'What is a doughnut?', a: 'Spinning the bike in a circle on the rear wheel.' },
  { q: 'What is a pace lap?', a: 'A lap before the start to warm tyres and form the grid.' },
  { q: 'What is a formation lap?', a: 'Same as pace lap; lap before the race start.' },
  { q: 'What is a jump start?', a: 'Moving before the start signal; usually a penalty.' },
  { q: 'What is a false start?', a: 'Starting before the signal; may result in penalty or restart.' },
  { q: 'What is a restart?', a: 'Race stopped and started again (e.g. after red flag).' },
  { q: 'What is a wet race?', a: 'Race run in rain or on wet track.' },
  { q: 'What are wet tyres?', a: 'Tyres designed for rain and wet track.' },
  { q: 'What are slicks?', a: 'Tyres with no tread, for dry conditions.' },
  { q: 'What are intermediate tyres?', a: 'Tyres for damp or drying conditions.' },
  { q: 'What is tyre warmers?', a: 'Electric blankets used to heat tyres before going on track.' },
  { q: 'What is tyre pressure?', a: 'The air pressure in the tyre; critical for grip and wear.' },
  { q: 'What is a compound?', a: 'The rubber mix of a tyre (soft, medium, hard).' },
  { q: 'What is a front tyre?', a: 'The tyre on the front wheel.' },
  { q: 'What is a rear tyre?', a: 'The tyre on the rear wheel.' },
  { q: 'What is a sprocket?', a: 'A toothed wheel that drives or is driven by the chain.' },
  { q: 'What is gearing?', a: 'The choice of sprocket sizes (and gear ratios) for speed vs acceleration.' },
  { q: 'What is a gear ratio?', a: 'The ratio between engine speed and wheel speed in a given gear.' },
  { q: 'What is top speed?', a: 'The maximum speed the bike can reach.' },
  { q: 'What is corner speed?', a: 'The speed through a corner.' },
  { q: 'What is braking distance?', a: 'The distance needed to slow for a corner.' },
  { q: 'What is a braking marker?', a: 'A board or object trackside showing where to start braking.' },
  { q: 'What is turn-in point?', a: 'Where the rider begins to lean and turn into a corner.' },
  { q: 'What is exit speed?', a: 'The speed at which the bike leaves a corner.' },
  { q: 'What is drive?', a: 'Acceleration out of a corner.' },
  { q: 'What is a straight?', a: 'A long straight section of track.' },
  { q: 'What is a hairpin?', a: 'A very tight corner, often 180 degrees.' },
  { q: 'What is an esses?', a: 'A series of S-shaped bends.' },
  { q: 'What is a kink?', a: 'A slight bend in an otherwise straight section.' },
  { q: 'What is a bus stop?', a: 'A tight chicane, often added to slow a straight.' },
  { q: 'What is a stadium section?', a: 'Part of the track near the main grandstand.' },
  { q: 'What is a pit building?', a: 'The building housing team garages and race control.' },
  { q: 'What is race control?', a: 'The central office that runs the event and makes decisions.' },
  { q: 'What is a scrutineer?', a: 'An official who checks bikes for technical compliance.' },
  { q: 'What is parc fermé?', a: 'A closed area where bikes are held after qualifying or race for inspection.' },
  { q: 'What is technical inspection?', a: 'Checking that bikes meet the rules.' },
  { q: 'What is minimum weight?', a: 'The minimum combined weight of bike and rider in some classes.' },
  { q: 'What is fuel capacity?', a: 'Maximum amount of fuel allowed (in some series).' },
  { q: 'What is a rev limit?', a: 'Maximum engine rpm allowed by the rules.' },
  { q: 'What is a spec ECU?', a: 'A standard electronic control unit mandated by the rules.' },
  { q: 'What is a wing in MotoGP?', a: 'Aerodynamic winglets on the fairing.' },
  { q: 'What is downforce?', a: 'Aerodynamic force pushing the bike toward the track.' },
  { q: 'What is drag?', a: 'Air resistance that slows the bike.' },
  { q: 'What is a wind tunnel?', a: 'A facility to test aerodynamics.' },
  { q: 'What is a test session?', a: 'Track time used for development rather than a race weekend.' },
  { q: 'What is pre-season testing?', a: 'Testing before the championship begins.' },
  { q: 'What is a shakedown?', a: 'A brief test to check that everything works.' },
  { q: 'What is a race weekend?', a: 'The days from arrival to the final race at a round.' },
  { q: 'What is a round?', a: 'One event in a championship (e.g. one Grand Prix).' },
  { q: 'What is a double header?', a: 'Two races at the same venue on consecutive days or same weekend.' },
  { q: 'What is a triple crown?', a: 'Winning rider, constructor, and team titles (or similar set).' },
  { q: 'What is a backmarker?', a: 'A slower rider who is lapped by the leaders.' },
  { q: 'What is lapping?', a: 'When the leader overtakes a rider who is a full lap behind.' },
  { q: 'What is unlapping?', a: 'A lapped rider getting back on the lead lap (e.g. under safety car).' },
  { q: 'What is a lead?', a: 'The margin by which the first rider is ahead.' },
  { q: 'What is a gap?', a: 'The time or distance between two riders.' },
  { q: 'What is closing the gap?', a: 'Reducing the time/distance to the rider ahead.' },
  { q: 'What is an overtake?', a: 'Passing another rider.' },
  { q: 'What is a block pass?', a: 'An overtake by positioning the bike to block the other rider\'s line.' },
  { q: 'What is an outbraking move?', a: 'Passing by braking later into a corner.' },
  { q: 'What is a dive bomb?', a: 'A very late, aggressive overtake into a corner.' },
  { q: 'What is clean air?', a: 'Air with no turbulence from another bike; better for cooling and aero.' },
  { q: 'What is dirty air?', a: 'Turbulent air behind another bike.' },
  { q: 'What is a tow?', a: 'Following another bike to get a slipstream (e.g. in qualifying).' },
  { q: 'What is a draft?', a: 'Same as slipstream; riding in the wake of another bike.' },
  { q: 'What is a stint?', a: 'A period of riding between pit stops (in endurance or long races).' },
  { q: 'What is an endurance race?', a: 'A long race (e.g. 6, 12, or 24 hours) often with multiple riders per bike.' },
  { q: 'What is a relay?', a: 'In endurance, when one rider hands the bike to another.' },
  { q: 'What is Le Mans 24h (bikes)?', a: 'The 24 Hours of Le Mans for motorcycles (endurance).' },
  { q: 'What is the Bol d\'Or?', a: 'A famous 24-hour motorcycle endurance race.' },
  { q: 'What is the Suzuka 8 Hours?', a: 'A prestigious 8-hour endurance race at Suzuka, Japan.' },
  { q: 'What is a factory bike?', a: 'A bike built and supported by the manufacturer for racing.' },
  { q: 'What is a satellite team?', a: 'A team that runs bikes (often current or previous factory) with less factory support.' },
  { q: 'What is a customer bike?', a: 'A racing bike sold to private teams by the manufacturer.' },
  { q: 'What is a CRT?', a: 'Claiming Rule Team; past MotoGP class for cost-cutting.' },
  { q: 'What is Open class?', a: 'A MotoGP class with more technical freedom and concessions.' },
  { q: 'What is a concession?', a: 'Extra testing or development allowed for struggling manufacturers.' },
  { q: 'What is a winglet?', a: 'Small aerodynamic wing on the fairing.' },
  { q: 'What is ride height?', a: 'How high the bike sits; can be adjusted for aero or handling.' },
  { q: 'What is holeshot?', a: 'Being first into the first corner from the start.' },
  { q: 'What is a holeshot device?', a: 'Device that lowers the rear to improve launch.' },
  { q: 'What is launch control?', a: 'Electronic aid for optimal race starts.' },
  { q: 'What is a start device?', a: 'System to improve acceleration from a standstill.' },
  { q: 'What is warmers?', a: 'Tyres warmers; blankets to heat tyres.' },
  { q: 'What is a debrief?', a: 'Meeting after a session to review data and plan.' },
  { q: 'What is data logging?', a: 'Recording telemetry (speed, throttle, brake, etc.) for analysis.' },
  { q: 'What is telemetry?', a: 'Data sent from the bike to the pits in real time.' },
  { q: 'What is a dash?', a: 'The instrument display on the bike.' },
  { q: 'What is a lap timer?', a: 'Device or display showing lap times.' },
  { q: 'What is sector time?', a: 'Time for a section of the lap (track is split into sectors).' },
  { q: 'What is split time?', a: 'Time at an intermediate point on the lap.' },
  { q: 'What is a personal best?', a: 'A rider\'s best lap time (or sector) so far.' },
  { q: 'What is an all-time lap record?', a: 'The fastest lap ever at the circuit in that class.' },
  { q: 'What is a circuit?', a: 'A closed track for racing.' },
  { q: 'What is a street circuit?', a: 'A circuit made from closed public roads.' },
  { q: 'What is a permanent circuit?', a: 'A purpose-built track, not temporary.' },
  { q: 'What is an oval?', a: 'A track shaped like an oval (common in US).' },
  { q: 'What is a road course?', a: 'A circuit with left and right turns (as opposed to oval).' },
  { q: 'What is a roval?', a: 'A track combining oval and road course (e.g. some NASCAR).' },
  { q: 'What is a corner?', a: 'A bend in the track.' },
  { q: 'What is a bend?', a: 'A corner or curve in the track.' },
  { q: 'What is a curve?', a: 'A section of track that is not straight.' },
  { q: 'What is camber?', a: 'The angle of the track surface (banking) in a corner.' },
  { q: 'What is banking?', a: 'When the track is tilted in a corner (like a banked turn).' },
  { q: 'What is a crown?', a: 'The raised middle of the road; can affect drainage and line.' },
  { q: 'What is a bump?', a: 'An uneven spot on the track surface.' },
  { q: 'What is a seam?', a: 'Where two sections of track join; can be slippery.' },
  { q: 'What is a painted line?', a: 'Line on the track; often slippery when wet.' },
  { q: 'What is a kerb?', a: 'The raised edge (often red and white) at the track boundary.' },
  { q: 'What is a rumble strip?', a: 'Strip of bumps before the kerb to warn riders.' },
  { q: 'What is an astroturf?', a: 'Artificial grass sometimes used in run-off.' },
  { q: 'What is tarmac?', a: 'The paved track surface.' },
  { q: 'What is asphalt?', a: 'Same as tarmac; the track surface.' },
  { q: 'What is a pit lane speed limit?', a: 'The maximum speed allowed in the pit lane.' },
  { q: 'What is a pit lane?', a: 'The lane where teams service the bikes during a stop.' },
  { q: 'What is a garage?', a: 'The team\'s enclosed space in the pit building.' },
  { q: 'What is a pit wall?', a: 'The wall between the pit lane and the track where team stands.' },
  { q: 'What is a pit board?', a: 'Board held out to show the rider information (lap time, position, etc.).' },
  { q: 'What is a lollipop?', a: 'The sign held in front of the bike during a pit stop (go/hold).' },
  { q: 'What is a fuel rig?', a: 'Equipment used to refuel the bike in the pits.' },
  { q: 'What is a tyre gun?', a: 'Pneumatic tool for quickly removing and fitting wheel nuts.' },
  { q: 'What is a wheel change?', a: 'Replacing a wheel (and tyre) during a pit stop.' },
  { q: 'What is a rider change?', a: 'In endurance, when one rider gets off and another gets on.' },
  { q: 'What is a leather?', a: 'A one- or two-piece suit worn for protection.' },
  { q: 'What is a back protector?', a: 'Armour worn inside or outside the leathers on the back.' },
  { q: 'What is a chest protector?', a: 'Armour for the chest and ribs.' },
  { q: 'What is a neck brace?', a: 'Device to support the neck in a crash.' },
  { q: 'What are racing boots?', a: 'Stiff, protective boots for riding.' },
  { q: 'What are racing gloves?', a: 'Reinforced gloves for riding.' },
  { q: 'What is a helmet?', a: 'Protective headgear; mandatory and often must meet standards.' },
  { q: 'What is a visor?', a: 'The clear or tinted shield on the front of the helmet.' },
  { q: 'What is a tear-off?', a: 'A thin plastic sheet on the visor that can be removed when dirty.' },
  { q: 'What is a pinlock?', a: 'Insert that reduces visor fogging.' },
  { q: 'What is an air fence?', a: 'Inflatable barrier to absorb impact.' },
  { q: 'What is a catch fence?', a: 'Fence designed to catch debris or slow a bike.' },
  { q: 'What is a tyre barrier?', a: 'Stack of tyres used as a soft barrier.' },
  { q: 'What is a TecPro barrier?', a: 'Type of plastic barrier that absorbs impact.' },
  { q: 'What is an ambulance point?', a: 'Designated spot for medical support.' },
  { q: 'What is a medical centre?', a: 'On-track facility for immediate medical care.' },
  { q: 'What is FIM?', a: 'Fédération Internationale de Motocyclisme; world governing body for motorcycle sport.' },
  { q: 'What is FIM Europe?', a: 'European arm of the FIM.' },
  { q: 'What is a national federation?', a: 'Country-level body (e.g. AMA, ACU) under the FIM.' },
  { q: 'What is the AMA?', a: 'American Motorcyclist Association.' },
  { q: 'What is the ACU?', a: 'Auto-Cycle Union; UK governing body for motorcycle sport.' },
  { q: 'What is Dorna?', a: 'Company that holds the commercial rights to MotoGP and WorldSBK.' },
  { q: 'What is a promoter?', a: 'Entity that organizes and promotes a race or series.' },
  { q: 'What is a sponsor?', a: 'Company that pays for branding on bike, leathers, or team.' },
  { q: 'What is a livery?', a: 'The paint scheme and sponsor logos on the bike.' },
  { q: 'What is a number board?', a: 'Panel showing the rider\'s number.' },
  { q: 'What is a rider number?', a: 'The number a rider uses (often chosen or assigned).' },
  { q: 'What is a legacy number?', a: 'In MotoGP, a permanent number for a champion or notable rider.' },
  { q: 'What is a race number?', a: 'The number displayed on the bike for that race/series.' },
];

export const HARD_QA = [
  { q: 'In what year did Ernst Henne set the motorcycle world speed record at 279.5 km/h on a supercharged BMW?', a: '1937' },
  { q: 'Who was the first non-British rider to win the Senior TT on the Isle of Man?', a: 'Georg "Schorsch" Meier' },
  { q: 'Which BMW rider won the European championship title in 1938 on a supercharged racing motorcycle?', a: 'Georg "Schorsch" Meier' },
  { q: 'In what year did Wilhelm Noll and Fritz Cron win the first world championship title for BMW in the sidecar class?', a: '1954' },
  { q: 'Who coined the term "superbike" in Cycle Guide Magazine?', a: 'Bob Braverman' },
  { q: 'In what year was the term "superbike" first used in Cycle Guide Magazine?', a: '1969' },
  { q: 'Who won the first US Superbike Championship title?', a: 'Reg Pridmore' },
  { q: 'In what year was the first season of the US Superbike Championship?', a: '1976' },
  { q: 'Which BMW model was the first series-production motorcycle developed in a wind tunnel?', a: 'R 100 RS' },
  { q: 'In what year did BMW Motorrad announce its participation in the Superbike World Championship?', a: '2008' },
  { q: 'Who won the Superstock 1000 FIM Cup on an S 1000 RR in 2012?', a: 'Sylvain Barrier' },
  { q: 'Which Italian rider won six races in the 2012 Superbike season on a BMW?', a: 'Marco Melandri' },
  { q: 'Who was BMW\'s first ever winner of a racing event for the Bavarian Motor Works?', a: 'Rudolf Schleicher' },
  { q: 'In what year did Rudolf Schleicher win the best time of the day at the Mittenwalder Steig mountain race?', a: '1924' },
  { q: 'Which BMW model did Max Friz ride in the "Race through Bavaria\'s Mountains" in 1923?', a: 'R 32' },
  { q: 'How many world-best performances did Ernst Henne achieve on BMW?', a: '75' },
  { q: 'For how many years did Ernst Henne\'s 1937 speed record remain in place?', a: '14 years' },
  { q: 'Who finished second to Schorsch Meier at the Senior TT in 1939?', a: 'Jock West' },
  { q: 'Which rider won the German championship in 1947 on a BMW?', a: 'Schorsch Meier' },
  { q: 'How many world championship titles did Klaus Enders win in the sidecar class?', a: 'Six' },
  { q: 'Between 1954 and 1974, how many rider classifications did BMW racing combinations win?', a: '19' },
  { q: 'Between 1954 and 1974, how many manufacturer\'s championships did BMW win in sidecar?', a: '20' },
  { q: 'Who won the 200-mile Daytona race in the first US Superbike season (1976)?', a: 'Steve McLaughlin' },
  { q: 'Which BMW model did Reg Pridmore ride to the first US Superbike title?', a: 'BMW R 90 S' },
  { q: 'In what year did the BMW R 80 G/S launch to the public?', a: '1980' },
  { q: 'Who won the European Offroad Championship on an 800-cc BMW in the year the R 80 G/S was launched?', a: 'Rolf Witthöft' },
  { q: 'Who won the motorcycle classification of the Paris-Dakar in 1981 on a BMW?', a: 'Hubert Auriol' },
  { q: 'Who won the Paris-Dakar motorcycle class in 1984 and 1985 on a BMW?', a: 'Gaston Rahier' },
  { q: 'In what year did Richard Sainct win the Paris-Dakar on a BMW F 650?', a: '1999' },
  { q: 'How many kilometres was the 1999 Paris-Dakar that Richard Sainct won?', a: '9022' },
  { q: 'Who won the one-cylinder class of the TT on the Isle of Man in 1997, 1998 and 1999 on a Chrysalis F 650?', a: 'Dave Morris' },
  { q: 'In what year was the BMW Motorrad BoxerCup first held as an international event?', a: '2001' },
  { q: 'Who won the BMW Motorrad BoxerCup in 2001 and 2002?', a: 'Stephane Mertens' },
  { q: 'In what year did the BMW Motorrad BoxerCup become the BMW Motorrad PowerCup with the K 1200 R?', a: '2005' },
  { q: 'What power did the BMW K 1200 R have in the PowerCup?', a: '120 kW (163 hp)' },
  { q: 'Who took the runner-up title in the E2 class of the World Enduro Championship in 2009 on a BMW G 450 X?', a: 'Juha Salminen' },
  { q: 'In what year did the BMW Motorrad Motorsport Endurance team make its debut at the 24 Hours of Le Mans with the HP2 Sport?', a: '2007' },
  { q: 'Who were the three riders who finished sixteenth overall and won the open class at the 24 Hours of Le Mans in 2007 for BMW?', a: 'Markus Barth, Thomas Hinterreiter and Rico Penzkofer' },
  { q: 'Where are the BMW Motorrad Motorsport headquarters?', a: 'Stephanskirchen' },
  { q: 'Who debuted for the BMW Motorrad motorsport team at Phillip Island in 2009 with Troy Corser?', a: 'Ruben Xaus' },
  { q: 'What was Troy Corser\'s fastest lap time at Phillip Island in the 2009 season opener (in minutes)?', a: '1:32.726' },
  { q: 'Who won nine of ten heats in the Superstock 1000 FIM Cup on an S 1000 RR in 2010?', a: 'Ayrton Badovini' },
  { q: 'Who joined Troy Corser at BMW for the 2011 Superbike World Championship?', a: 'Leon Haslam' },
  { q: 'Who is Leon Haslam\'s father, known as "Rocket Ron"?', a: 'Ron Haslam' },
  { q: 'Which team came second in the FIM Endurance World Championship in 2011 with an S 1000 RR?', a: 'BMW Motorrad France 99' },
  { q: 'Who was runner-up in the IDM in 2011 for BMW?', a: 'Michael Ranseder' },
  { q: 'Who returned to the World Sidecar Championship with BMW in 2012 after over thirty years?', a: 'Jörg Steinhausen' },
  { q: 'Who is Jörg Steinhausen\'s father, the two-times world sidecar champion?', a: 'Rolf Steinhausen' },
  { q: 'In which years did Rolf Steinhausen win the world sidecar championship?', a: '1975 and 1976' },
  { q: 'Who was Jörg Steinhausen\'s partner in the 2012 BMW sidecar?', a: 'Grégory Cluze' },
  { q: 'How many points did the second-placed manufacturer have in the 2012 IDM behind BMW?', a: '403 points behind (BMW had 644)' },
  { q: 'Who became the 2012 IDM superbike champion on a BMW?', a: 'Nigon Erwan' },
  { q: 'What is the Tourist Trophy?', a: 'The Isle of Man TT; a time-trial motorcycle race on public roads.' },
  { q: 'Where is the Isle of Man?', a: 'An island in the Irish Sea between Great Britain and Ireland.' },
  { q: 'What is the Senior TT?', a: 'The premier (historically 500 cc) class of the Isle of Man TT.' },
  { q: 'What is the Junior TT?', a: 'A TT class; historically for smaller capacity.' },
  { q: 'What is the Superbike TT?', a: 'A TT race for superbike-class machines.' },
  { q: 'What is the Supersport TT?', a: 'A TT race for supersport 600 cc machines.' },
  { q: 'What is the Lightweight TT?', a: 'A TT class for lighter/smaller bikes.' },
  { q: 'What is the Sidecar TT?', a: 'The TT race for sidecar machines.' },
  { q: 'What is the Zero TT?', a: 'TT race for electric motorcycles.' },
  { q: 'What is the Mountain Course?', a: 'The 37.73-mile road course used for the Isle of Man TT.' },
  { q: 'How long is the Isle of Man TT Mountain Course in miles?', a: '37.73 miles' },
  { q: 'What is Bray Hill?', a: 'A steep descent at the start of the TT course in Douglas.' },
  { q: 'What is the Bungalow?', a: 'A section and landmark on the TT Mountain Course.' },
  { q: 'What is Creg-ny-Baa?', a: 'A corner and pub on the TT course.' },
  { q: 'What is Ballaugh Bridge?', a: 'A bridge on the TT course where riders often get airborne.' },
  { q: 'What is a jump on the TT course?', a: 'A rise in the road that can make the bike leave the ground.' },
  { q: 'What is the 200-mile Daytona race?', a: 'The Daytona 200; a famous American motorcycle race at Daytona International Speedway.' },
  { q: 'Where is Daytona International Speedway?', a: 'Daytona Beach, Florida, USA.' },
  { q: 'What is the Suzuka 8 Hours?', a: 'A prestigious 8-hour endurance race at Suzuka, Japan.' },
  { q: 'Where is the Bol d\'Or held?', a: 'France (Circuit Paul Ricard).' },
  { q: 'What is the Paris-Dakar rally?', a: 'A long-distance rally (originally Paris to Dakar); now held in South America or Saudi Arabia.' },
  { q: 'Who won the women\'s classification at the Cape Town rally in 1992 on a BMW R 100 GS?', a: 'Jutta Kleinschmidt' },
  { q: 'How many kilometres was the Cape Town rally route that Jutta Kleinschmidt won in 1992?', a: '12,700 km' },
  { q: 'What does DOHC stand for?', a: 'Double overhead camshaft (two camshafts per cylinder head).' },
  { q: 'What does OHV stand for?', a: 'Overhead valve.' },
  { q: 'What is a supercharger on a motorcycle?', a: 'A compressor that forces more air into the engine to increase power.' },
  { q: 'What is a compressor in racing?', a: 'A supercharger or device that compresses intake air.' },
  { q: 'What is the Monolever?', a: 'BMW\'s single-sided swingarm design on the rear wheel.' },
  { q: 'What is the Paralever?', a: 'BMW\'s later evolution of the single-sided rear suspension.' },
  { q: 'What is shaft drive on a BMW Boxer?', a: 'A driveshaft that connects the gearbox to the rear wheel.' },
  { q: 'What is the Boxer engine layout?', a: 'Cylinders opposed horizontally, with pistons moving in and out like boxer fists.' },
  { q: 'What is the R 32?', a: 'The first BMW motorcycle (1923); a 500 cc flat-twin.' },
  { q: 'What is the R 37?', a: 'A BMW racing model with OHV cylinder head by Rudolf Schleicher (1920s).' },
  { q: 'What is the R 16?', a: 'A BMW solo and sidecar model used in the 1930s six-day races.' },
  { q: 'What is the R 80 G/S?', a: 'The BMW model that established the large enduro segment (1980).' },
  { q: 'What is the R 90 S?', a: 'The BMW model used in the first US Superbike Championship (1976).' },
  { q: 'What is the R 100 RS?', a: 'The first series-production motorcycle developed in a wind tunnel (BMW).' },
  { q: 'What is the R 100 GS?', a: 'A BMW large enduro; Jutta Kleinschmidt won on one in 1992.' },
  { q: 'What is the R 1100 S?', a: 'The BMW model used in the BoxerCup.' },
  { q: 'What is the K 1200 R?', a: 'The "most powerful naked bike" used in the BMW PowerCup (120 kW).' },
  { q: 'What is the F 650?', a: 'A BMW single-cylinder model; used in Paris-Dakar and BoxerCup era.' },
  { q: 'What is the F 650 RR?', a: 'Rally version of the F 650 used by BMW in Paris-Dakar.' },
  { q: 'What is the R 900 RR?', a: 'BMW\'s rally version of the four-valve Boxer for Paris-Dakar.' },
  { q: 'What is the G 450 X?', a: 'BMW\'s sport enduro for the 450 cc class.' },
  { q: 'What is the HP2 Sport?', a: 'The first series-production Boxer with DOHC; used at Le Mans 24h by BMW.' },
  { q: 'What is the S 1000 RR?', a: 'BMW\'s four-cylinder superbike; used in WorldSBK and many national series.' },
  { q: 'What is the R 80 G/S predecessor in development?', a: 'The BMW GS 800 (off-road development by Herbert Schek).' },
  { q: 'Who developed the optimum off-road BMW that led to the R 80 G/S?', a: 'Herbert Schek' },
  { q: 'Name three well-known BMW off-road riders in the 1960s.', a: 'Sebastian Nachtmann, Manfred Sensburg, Herbert Schek' },
  { q: 'Who won the German 250-cc class championship for BMW in 1925?', a: 'BMW with the R 39' },
  { q: 'In what year did Rudolf Schleicher win the gold medal at the six-day race in Buxton, England?', a: '1926' },
  { q: 'Where did Paul Köppen and Ernst Henne win for BMW in Italy?', a: 'The Sicilian Targa Florio' },
  { q: 'In what year did the BMW team win the nations ranking in the international six-day race at Llandrindod Wells?', a: '1933' },
  { q: 'Where is Llandrindod Wells?', a: 'Wales' },
  { q: 'In what year did Ernst Henne set his first world speed record of 216.75 km/h on a 750-cc BMW?', a: '1929' },
  { q: 'Where did Ernst Henne set the 216.75 km/h record?', a: 'The Ingolstädter Landstrasse near Munich' },
  { q: 'What was the capacity of the BMW that took Ernst Henne to 279.5 km/h in 1937?', a: '500 cc' },
  { q: 'Where did Andrea Mayer take the women\'s Paris-Dakar title for the third time in a row?', a: 'In the 2000 Paris-Dakar (Dakar to Cairo)' },
  { q: 'Who came second in the 2000 Paris-Dakar for BMW?', a: 'Oscar Gallardo' },
  { q: 'Who finished fourth in the 2000 Paris-Dakar for BMW?', a: 'Jean Brucy' },
  { q: 'Who achieved third place on the R 900 RR at its debut with Jimmy Lewis?', a: 'Jimmy Lewis' },
  { q: 'What was the Chrysalis team\'s F 650 frame made of?', a: 'Aluminium bridge-frame' },
  { q: 'How much did Dave Morris\'s Chrysalis F 650 weigh (in kg)?', a: '134 kg' },
  { q: 'What power did Dave Morris\'s TT-winning Chrysalis F 650 have?', a: '59 kW (80 hp)' },
  { q: 'Who created the PAMI team design for Herbert Enzinger in 1995?', a: 'The German PAMI team' },
  { q: 'How much did Herbert Enzinger\'s 1995 PAMI bike weigh?', a: 'No more than 115 kg' },
  { q: 'What power did Herbert Enzinger\'s 1995 bike have?', a: '63 kW (85 hp)' },
  { q: 'In what year did Herbert Enzinger finish third in the Daytona Speedweek?', a: '1995' },
  { q: 'How many heats were in the 2001 BMW Motorrad BoxerCup?', a: 'Seven' },
  { q: 'How many riders competed in the 2001 BoxerCup from across Europe?', a: '30' },
  { q: 'Who was the ambassador of the BMW Motorrad BoxerCup and took to the handlebars as a guest?', a: 'Randy Mamola' },
  { q: 'In what year was the BoxerCup first held in the USA?', a: '2003' },
  { q: 'Where was the BoxerCup held in the USA in 2003?', a: 'At the 200-mile Daytona meeting' },
  { q: 'How many world championship heats did the BMW Motorrad team win in the open class in 2007?', a: 'Four out of five' },
  { q: 'In what year did Walter Zeller last appear as a BMW works rider?', a: '1957' },
  { q: 'How many years after Walter Zeller\'s last works appearance did the HP2 Sport race at Le Mans?', a: 'Fifty years (2007)' },
  { q: 'Who won the 2009 World Enduro Championship E class after leaving BMW for Husqvarna?', a: 'Juha Salminen' },
  { q: 'In what year did Juha Salminen win the world championship in the E class?', a: '2011' },
  { q: 'Which brand was part of BMW Motorrad when Juha Salminen won on a Husqvarna?', a: 'Husqvarna' },
  { q: 'How many pole positions did Ayrton Badovini have in the 2010 Superstock 1000 FIM Cup?', a: 'Eight' },
  { q: 'How many fastest laps did Ayrton Badovini have in 2010 in that series?', a: 'Six' },
  { q: 'In what position did Leon Haslam finish the 2011 world championship?', a: 'Fifth' },
  { q: 'How many times did Leon Haslam get on the podium in 2011?', a: 'Three' },
  { q: 'In what position did Marco Melandri finish the 2012 world championship?', a: 'Third' },
  { q: 'How many racing victories did Marco Melandri secure in 2012?', a: 'Six' },
  { q: 'Where did Jörg Steinhausen and Grégory Cluze finish in the 2012 World Sidecar Championship?', a: 'Runners up' },
  { q: 'What engine did the 2012 BMW sidecar use?', a: 'S 1000 RR engine' },
];
