/**
 * Extra unique Australian trivia. Appended to AUS_Q&A.json so existing indices stay stable.
 * Facts are catalog-backed (tracks) or well-known championship history.
 */

function q(question, correct, wrongs, joke, rating) {
  const options = [correct, ...wrongs.slice(0, 3), joke].filter((s) => typeof s === 'string' && s.length > 0);
  return {
    question,
    options,
    correct_index: 0,
    difficulty_rating: rating,
    difficulty: rating <= 4 ? 'easy' : 'hard',
    source: 'au-extra',
  };
}

export const AU_EXTRA_TRIVIA = [
  q('What does ASBK stand for?', 'Australian Superbike Championship', ['Australian Sidecar Bike Klassic', 'Asian Superbike Knockout', 'Aussie Super Bike Kings'], 'Alien Space Bike Knights', 1),
  q('Which organisation publishes the Manual of Motorcycle Sport in Australia?', 'Motorcycling Australia', ['Motorsport UK', 'FIM Europe', 'NASCAR'], 'The local fish-and-chip shop', 2),
  q('What does MoMS stand for?', 'Manual of Motorcycle Sport', ['Moto Official Marshall Sheet', 'Motorcycle Owners Membership Scheme', 'Main Oval Motocross Series'], 'My Old Mate\'s Scooter', 2),
  q('Where is the Australian Motorcycle Grand Prix usually held?', 'Phillip Island', ['Bathurst', 'Silverstone', 'Assen'], 'The car park at Bunnings', 1),
  q('In which Australian state is Phillip Island Grand Prix Circuit?', 'Victoria', ['New South Wales', 'Queensland', 'South Australia'], 'Middle-earth', 1),
  q('Which direction is Phillip Island Grand Prix Circuit raced?', 'Anticlockwise', ['Clockwise', 'Figure-eight', 'Both directions each lap'], 'Whatever the wind says', 3),
  q('About how long is the Phillip Island Grand Prix Circuit?', '4.45 km', ['2.2 km', '7.77 km', '12 km'], 'From the couch to the fridge', 3),
  q('What is Turn 1 at Phillip Island called?', 'Doohan Corner', ['Hell Corner', 'Cat Corner', 'Murray\'s Corner'], 'The bit where you close your eyes', 3),
  q('Which Phillip Island corner is named after Casey Stoner?', 'Stoner Corner (Turn 3)', ['Lukey Heights', 'Southern Loop', 'Siberia'], 'The pie stand', 4),
  q('Miller Corner at Phillip Island was previously known as what?', 'Honda Corner', ['Yamaha Hairpin', 'Ducati Dip', 'Suzuki Sweep'], 'The kebab van', 5),
  q('Which fast, exposed Phillip Island corner is nicknamed Siberia?', 'Turn 5', ['Doohan Corner', 'MG Hairpin', 'Gardner\'s'], 'The merch tent', 6),
  q('What is the uphill complex at Phillip Island after Hayshed?', 'Lukey Heights', ['The Dipper', 'The Cutting', 'Skyline'], 'A really steep driveway', 5),
  q('Which tight right at Phillip Island is MG Hairpin?', 'Turn 9', ['Turn 1', 'Turn 4', 'Turn 11'], 'The roundabout near the ferry', 6),
  q('Turn 11 at Phillip Island is also known as whose corner?', 'Gardner\'s', ['Rossi\'s', 'Marquez Corner', 'Bayliss Bend'], 'Your uncle\'s driveway', 4),
  q('Who was the first Australian to win the 500cc world championship?', 'Wayne Gardner', ['Mick Doohan', 'Casey Stoner', 'Jack Miller'], 'Crocodile Dundee', 5),
  q('In which year did Wayne Gardner win the 500cc world title?', '1987', ['1998', '2007', '2011'], 'The year sliced bread was invented', 7),
  q('How many consecutive 500cc titles did Mick Doohan win?', 'Five (1994–1998)', ['Two', 'Three', 'Seven'], 'Enough to fill a esky', 6),
  q('Casey Stoner won MotoGP titles in which years?', '2007 and 2011', ['1987 and 1988', '1994 and 1995', '2020 and 2021'], 'Every year he remembered to set an alarm', 6),
  q('Casey Stoner\'s first MotoGP title was with which manufacturer?', 'Ducati', ['Honda', 'Yamaha', 'Suzuki'], 'A lawnmower brand', 5),
  q('How many WorldSBK rider titles has Troy Bayliss won?', 'Three', ['One', 'Five', 'Zero'], 'He only raced lawnmowers', 6),
  q('Jack Miller is from which Australian city?', 'Townsville', ['Hobart', 'Perth', 'Canberra'], 'The moon base', 4),
  q('Remy Gardner is the son of which Australian world champion?', 'Wayne Gardner', ['Mick Doohan', 'Casey Stoner', 'Troy Corser'], 'The bloke who invented Vegemite', 4),
  q('What class did Remy Gardner win a world title in during 2021?', 'Moto2', ['MotoGP', 'Moto3', 'WorldSBK'], 'Lawnmower GP', 7),
  q('Troy Corser is a former world champion in which series?', 'World Superbike (WorldSBK)', ['MotoGP', 'Moto2', 'Isle of Man TT'], 'MasterChef', 5),
  q('ASBK\'s premier class is usually called what?', 'Superbike', ['MotoGP', 'Formula 1', 'Supercross'], 'Very Fast Bicycles', 2),
  q('Which ASBK class is a common step below Superbike?', 'Supersport', ['NASCAR Truck', 'Rally1', 'MotoE only'], 'The coffee queue', 3),
  q('Which junior cup often supports ASBK at Australian circuits?', 'Oceania Junior Cup', ['MotoGP Rookies only', 'F2 Academy', 'WRC Juniors'], 'Under-8s scooter club', 5),
  q('The Bend Motorsport Park is in which state?', 'South Australia', ['Victoria', 'Western Australia', 'Tasmania'], 'Narnia', 2),
  q('The Bend International Circuit is about how long?', '4.95 km', ['2.16 km', '4.45 km', '7.77 km'], 'A decent walk to the bakery', 4),
  q('The Bend GT Circuit is about how long?', '7.77 km', ['3.12 km', '4.45 km', '2.2 km'], 'Around the block twice', 4),
  q('Which direction is The Bend International Circuit raced?', 'Clockwise', ['Anticlockwise', 'Either, randomly', 'Figure-eight'], 'Uphill both ways', 4),
  q('Sydney Motorsport Park (Eastern Creek) Gardner GP Circuit is about how long?', '4.5 km', ['1.9 km', '2.41 km', '6.213 km'], 'From pit wall to the kebab van', 4),
  q('Which direction is the Gardner GP Circuit at Sydney Motorsport Park?', 'Anticlockwise', ['Clockwise', 'Both ways at once', 'Oval only'], 'Follow the ibis', 4),
  q('What is the shorter 1.9 km layout at Sydney Motorsport Park called?', 'Druitt Circuit', ['Brabham Circuit', 'Gardner GP', 'GT Circuit'], 'The car-park loop', 7),
  q('Sydney Motorsport Park\'s ~3.0 km layout is the what Circuit?', 'Brabham Circuit', ['Druitt Circuit', 'Gardner GP', 'National Circuit'], 'The sausage-sizzle circuit', 7),
  q('Queensland Raceway is often nicknamed what?', 'The Paperclip', ['The Island', 'The Mountain', 'The Dipper'], 'The giant paper aeroplane', 3),
  q('Queensland Raceway is near which Queensland city?', 'Ipswich', ['Cairns', 'Darwin', 'Hobart'], 'Wagga-but-make-it-beach', 4),
  q('Queensland Raceway National Circuit is about how long?', '3.12 km', ['4.45 km', '7.77 km', '2.01 km'], 'A trip to the servo', 5),
  q('Which direction is Queensland Raceway raced?', 'Clockwise', ['Anticlockwise', 'Point-to-point', 'Either each session'], 'Whatever GPS suggests', 4),
  q('Turn 1 at Queensland Raceway is known as what?', 'Kitty\'s Corner', ['Doohan Corner', 'Hell Corner', 'Cat Corner'], 'The pie warmer', 6),
  q('Morgan Park Raceway is in which Queensland town?', 'Warwick', ['Byron Bay', 'Broome', 'Alice Springs'], 'A town that only exists on race weekends', 5),
  q('Morgan Park Circuit K is about how long?', '2.97 km', ['4.45 km', '6.213 km', '1.2 km'], 'The length of a good yarn', 6),
  q('Which direction is Morgan Park raced?', 'Clockwise', ['Anticlockwise', 'Downhill only', 'Figure-eight'], 'Ask the cattle', 5),
  q('One Raceway was previously known as which circuit?', 'Wakefield Park', ['Lakeside', 'Mallala', 'Sandown'], 'That paddock behind the pub', 3),
  q('One Raceway (Wakefield Park) is about how long?', '2.2 km', ['4.5 km', '7.77 km', '6.213 km'], 'Two laps of the shops', 5),
  q('One Raceway is near which NSW town?', 'Goulburn', ['Mildura', 'Cairns', 'Bunbury'], 'Wherever the UHF crackles', 6),
  q('Wanneroo Raceway is also known as what?', 'Barbagallo', ['Eastern Creek', 'The Bend', 'Mac Park'], 'The big roundabout', 3),
  q('In which state is Wanneroo Raceway?', 'Western Australia', ['Tasmania', 'Victoria', 'South Australia'], 'WA...iting for the ferry', 2),
  q('Wanneroo Raceway bike layout is about how long?', '2.41 km', ['4.45 km', '6.213 km', '7.77 km'], 'From the beach to the next beach', 5),
  q('Turn 1 at Wanneroo is called what?', 'Cat Corner', ['Doohan Corner', 'Hell Corner', 'Kitty\'s Corner'], 'The sand dune', 6),
  q('Kolb Corner (The Basin) is at which Australian circuit?', 'Wanneroo Raceway', ['Phillip Island', 'Bathurst', 'Hidden Valley'], 'A waterpark', 7),
  q('Mount Panorama Circuit is in which NSW city?', 'Bathurst', ['Newcastle', 'Wollongong', 'Albury'], 'A mountain that is actually a speed bump', 2),
  q('About how long is Mount Panorama?', '6.213 km', ['4.45 km', '2.41 km', '3.12 km'], 'Straight up and hope', 3),
  q('Which direction is Mount Panorama raced?', 'Clockwise', ['Anticlockwise', 'Down the mountain only', 'Either'], 'Gravity decides', 3),
  q('What is Turn 1 at Mount Panorama called?', 'Hell Corner', ['Doohan Corner', 'MG Hairpin', 'Cat Corner'], 'Heaven\'s car park', 3),
  q('Which long Bathurst straight runs down to The Chase?', 'Conrod Straight', ['Mountain Straight', 'Pit Straight only', 'Gardner Straight'], 'The driveway', 5),
  q('Forrest\'s Elbow is a famous corner at which circuit?', 'Mount Panorama (Bathurst)', ['Phillip Island', 'The Bend', 'Hidden Valley'], 'Your local IKEA', 4),
  q('The Dipper and Skyline are corners at which Australian circuit?', 'Mount Panorama (Bathurst)', ['Phillip Island', 'Wanneroo', 'Lakeside'], 'A ski resort', 5),
  q('Hidden Valley Raceway is in which city?', 'Darwin', ['Hobart', 'Adelaide', 'Geelong'], 'A valley that is not hidden at all', 3),
  q('Hidden Valley is in which Australian territory/state?', 'Northern Territory', ['ACT', 'Tasmania', 'Victoria'], 'The lost property office', 3),
  q('Hidden Valley Full Circuit is about how long?', '2.87 km', ['4.45 km', '6.213 km', '7.77 km'], 'A croc\'s lunch run', 5),
  q('Which direction is Hidden Valley raced?', 'Anticlockwise', ['Clockwise', 'Point-to-point', 'Figure-eight'], 'Follow the fruit bats', 5),
  q('Mallala Motorsport Park is in which state?', 'South Australia', ['Queensland', 'NSW', 'WA'], 'Wherever the dust blows', 3),
  q('Mallala\'s full circuit is about how long?', '2.6 km', ['4.95 km', '6.213 km', '1.0 km'], 'A sheep paddock diagonal', 6),
  q('McNamara Park (Mac Park) is near which SA city?', 'Mount Gambier', ['Broken Hill', 'Toowoomba', 'Launceston'], 'A cave that echoes "apex"', 6),
  q('Mac Park\'s main circuit is about how long?', '2.4 km', ['4.45 km', '7.77 km', '6.213 km'], 'Around the crater twice', 6),
  q('Broadford State Motorcycle Complex is in which state?', 'Victoria', ['Queensland', 'WA', 'Tasmania'], 'Wherever MA left the cones', 3),
  q('Broadford\'s main bike layout is about how long?', '2.16 km', ['4.5 km', '6.213 km', '7.77 km'], 'The length of a club briefing', 6),
  q('Winton Motor Raceway is in which state?', 'Victoria', ['SA', 'NT', 'Tasmania'], 'Winton-upon-Avon', 4),
  q('Winton\'s main circuit is about how long?', '3.0 km', ['4.45 km', '1.9 km', '7.77 km'], 'A country road with ideas', 6),
  q('Sandown Raceway is in which state?', 'Victoria', ['NSW', 'QLD', 'WA'], 'A beach with kerbs', 4),
  q('Which direction is Sandown National Circuit raced?', 'Anticlockwise', ['Clockwise', 'Either', 'Oval only'], 'Toward the grandstand pies', 6),
  q('Lakeside Park is in which state?', 'Queensland', ['Victoria', 'SA', 'Tasmania'], 'A lake that is actually a chicane', 4),
  q('Lakeside Park\'s full circuit is about how long?', '2.41 km', ['4.45 km', '6.213 km', '7.77 km'], 'A lap of the lake on a paddleboard', 6),
  q('Which direction is Lakeside Park raced?', 'Anticlockwise', ['Clockwise', 'Point-to-point', 'Figure-eight'], 'Whichever way the water flows', 6),
  q('Baskerville Raceway is in which state?', 'Tasmania', ['Victoria', 'WA', 'NT'], 'A basket of apexes', 4),
  q('Baskerville\'s full circuit is about how long?', '2.01 km', ['4.45 km', '6.213 km', '3.12 km'], 'Hobart to the next bakery', 7),
  q('Calder Park Raceway is in which state?', 'Victoria', ['NSW', 'QLD', 'SA'], 'A shopping-centre car park', 5),
  q('The historic Island Classic is held at which circuit?', 'Phillip Island', ['Bathurst', 'Assen', 'Laguna Seca'], 'A museum with a pit lane', 4),
  q('Who is Australia\'s national motorcycle sport governing body?', 'Motorcycling Australia (MA)', ['CAMS only', 'FIA', 'NASCAR Australia'], 'The bloke with the chequered tea towel', 2),
  q('A typical MA road-race weekend is run under which rule book?', 'The Manual of Motorcycle Sport (MoMS)', ['The F1 sporting regs', 'Isle of Man Highway Code', 'MotoGP-only technical regs'], 'Whoever shouted loudest at the riders briefing', 3),
  q('Phillip Island first hosted the Australian Motorcycle Grand Prix in which year?', '1989', ['1949', '1975', '2007'], 'The year the ferry learned to wheelie', 8),
  q('Which Australian won MotoGP titles with both Ducati and Honda?', 'Casey Stoner', ['Mick Doohan', 'Wayne Gardner', 'Jack Miller'], 'A very talented wallaby', 6),
  q('Doohan Corner is named after which five-time 500cc champion?', 'Mick Doohan', ['Wayne Gardner', 'Casey Stoner', 'Troy Bayliss'], 'A corner named after a donut', 3),
  q('Which Australian circuit is famous for sea winds and a long front straight?', 'Phillip Island', ['Hidden Valley', 'Mallala', 'Baskerville'], 'The wind tunnel at the airport', 2),
  q('Tailem Bend is the town nearest which major circuit?', 'The Bend Motorsport Park', ['Phillip Island', 'Wanneroo', 'Lakeside'], 'A bend in the Murray that sells slicks', 4),
  q('Eastern Creek is another name associated with which venue?', 'Sydney Motorsport Park', ['The Bend', 'Morgan Park', 'Mac Park'], 'A creek that red-flags you', 3),
  q('Which Australian circuit hosted MotoGP when the Australian GP is on the calendar?', 'Phillip Island Grand Prix Circuit', ['Mount Panorama', 'Queensland Raceway', 'Hidden Valley'], 'The MCG, but with kerbs', 1),
  q('ASBK rounds are commonly held at tracks such as Phillip Island and which Queensland paperclip?', 'Queensland Raceway', ['Silverstone', 'Mugello', 'Jerez'], 'A paperclip from Officeworks', 3),
  q('Which Tasmanian circuit often appears in Australian club and historic racing?', 'Symmons Plains and/or Baskerville', ['Phillip Island only', 'Assen', 'Brands Hatch'], 'A paddock that hibernates', 7),
  q('Broadford is run by Motorcycling Victoria as what kind of venue?', 'A dedicated motorcycle complex', ['An F1 street circuit', 'A speedway oval only', 'A motocross-only park'], 'A very loud golf course', 5),
  q('Which SA circuit is a long-time club racing venue north of Adelaide?', 'Mallala Motorsport Park', ['Phillip Island', 'Hidden Valley', 'Lakeside'], 'The O-Bahn, but faster', 5),
  q('Hayshed is a named corner at which Australian GP circuit?', 'Phillip Island', ['Bathurst', 'The Bend', 'SMP Gardner'], 'An actual hay shed', 4),
  q('Southern Loop is Turn 2 at which circuit?', 'Phillip Island', ['Wanneroo', 'Winton', 'Sandown'], 'A loop-the-loop at Luna Park', 4),
  q('Which Australian manufacturer-backed superbike series is the domestic premier road-race championship?', 'ASBK', ['MotoGP', 'WSBK only', 'British Superbike'], 'The Great Aussie Burnout Championship', 2),
];
